schedule:
  candle:
    one-minute: "5 * * * * *"
    three-minutes: "5 */3 * * * *"
    five-minutes: "5 */5 * * * *"
    fifteen-minutes: "5 */15 * * * *"
    thirty-minutes: "5 */15 * * * *"
    one-hour: "5 */15 * * * *"
    one-day: "5 */15 * * * *"
    increase-day: "30 */15 * * * *"
  order:
    all-minute: "1 * * * * *"
    one-minute: "30 * * * * *"
    three-minutes: "30 */3 * * * *"
    five-minutes: "30 */5 * * * *"
    fifteen-minutes: "30 */15 * * * *"
    thirty-minutes: "30 */30 * * * *"
    one-hour: "30 0 * * * *"
    one-day: "50 59 23 * * *"
  market: "5 0 0 * * *"
logging:
  level:
    com:
      lokiechart:
        www: warn

server:
  port: 3420